services:
  gateway:
    build: services/gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - USERS_SERVICE_URL=http://users:8081
      - PRODUCTS_SERVICE_URL=http://products:8082